### ISSUE TITLE
This plugin causes severe issues

### ISSUE THREAD

**Issue by mind-overflow** [Ssomar-Developement/SCore#3]
I noticed that every time you have to send a database query, you call this method:
```java
com.ssomar.score.data.Database.connect();
```

However, this method has a huge memory leak (and I/O file leak), because of this single line:
```java
// <...>
else conn = DriverManager.getConnection(urlLocal);
```

This is a huge issue because it opens a new database connection every single time, which means, for example:
- 2 new database connections everytime a player joins (PlayerJoinEvent), as per the plugin usage;
- 1 new database connection everytime a pleyr disconnects (PlayerQuitEvent), as per the plugin usage;
- many more examples (23 total usages of this method in the whole plugin).

Of course, without calling `connection.close();`, the connection is never closed and hogs system resources.
In my case, the server is a very powerful machine and doesn't crash because of ram, but because of this error:
```
Too many open files
```

I have lost a lot of data because of those crashes, and I had to use `lsof` Linux command to diagnose the issue.

Example (in class `CommandsHandler`):
```java
List<PlayerRunCommand> commands = PlayerCommandsQuery.selectCommandsForPlayer(Database.getInstance().connect(), p.getUniqueId());
```

You should do two things:
1. close the connection after you finish using it (by using `connection.close()`), but this is not suggested because opening a new connection every time is useless and also you have no easy way to close the connection as it's only accessible from the `connect()` method;
2. instead of opening a new connection every time, just open it once on plugin startup and save it in a static variable. Then, instead of using the `connect()` method, create a new `getConnection()` method, and return the static variable. Example:
```java
private static Connection connection;

// <other class methods and stuff>

public static void getConnection()
{
  if(this.connection != null && !this.connection.isClosed())
  {
    return this.connection;
  } else
  {
    // <retry connecting>
  }
}
```

**Comment by mind-overflow** [comment]
Example of how many database connections I have after about ~24 hours uptime:
```bash
# lsof > open_files.txt
# # grep -o 'SCore' open_files.txt | wc -l
1155386
```

About one million.

**Comment by mind-overflow** [comment]
Still no response after a week.

**Comment by mind-overflow** [comment]
Apparently, after more than a month, the issue and the relative suggested solution have not been considered yet.

**Comment by ssomar1607** [comment]
OMG, I never open github. I'm only active on my discord, and weird I have not received an email for your issue. Sorry for that (4 months ouch).

Thank you for your message ^^ Now that I know that, I will edit my code asap !

**Comment by mind-overflow** [comment]
@ssomar1607 no problem, this is the good thing about open source: you were busy doing other stuff, but since the code is available, i just compiled a fixed jar myself. Glad you noticed it, have a good day!
